# Ejercicio 4 - Aprendizaje Supervizado Clasificacion Parte I
## Inteligencia Artificial - Ing. en Sistemas de Información 
## UTN Facultad Regional Villa Maria
### Natalia Bruno - Legajo: 10683

1. Declarar una variable random_state igual al número de alumno en la hoja de cálculo "Entregas TPs" en el Google Drive de la materia.
2. Implementar un clasificador kNN.
3. Aplicarle z-score standarization a los datos. Dividir en conjunto de train y test y entrenar el clasificador con el sub-conjunto de datos de entrenamiento, mostrando el correspondiente error de test. Utilizar el correspondiente random_state.
4. Considere el caso donde un incorrecto diagnóstico de cáncer cuando la célula es benigna tiene un costo de 5, mientras que una errónea omisión de una célula maligna tiene un costo de 20. Modificar las salidas del clasificador para que el mismo realice la mayor reducción posible del costo por errores de clasificación, e imprimir dichas salidas. Ayuda: una forma es utilizar el método predicted_proba() para obtener las probabilidades.
5. Considerando el punto anterior, ampliar el código para que seleccione automáticamente o mediante iteraciones la cantidad de vecinos que minimiza el costo. Especificar cuál es el costo mínimo obtenido tras dicha minimización.

Fecha de entrega: 17/05/2017.
Nota: la resolución de los ejercicios es **individual**; en el caso de que dos ejercicios enviados contengan un código igual o muy similar (sin considerar los comentarios), se los considerará a ambos como desaprobados. La reutilización del código del notebook está permitida (por ejemplo para confeccionar gráficos).

In [26]:
# Punto 1: declaro una variable random_state con mi numero de alumno.
import numpy as np
rns = np.random.RandomState(2)

import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

X = data.data
y = data.target

# Las clases pueden ser de dos tipos:
# 0= maligno
# 1= benigno
print(data.target_names)

['malignant' 'benign']


In [27]:
# Punto 2: Implemento un clasificador kNN
from sklearn import neighbors
clf = neighbors.KNeighborsClassifier(n_neighbors=10, weights='distance')

# Punto 3: Aplico z-score standarization para normalizar los datos
from scipy import stats
X_s = stats.zscore(X)

In [28]:
from sklearn.model_selection import train_test_split

# Divido el conjunto en train, test
X_train, X_test, y_train, y_test = train_test_split(X_s, y, random_state= rns, test_size=0.2)

# Entreno el modelo con el sub-conjunto de datos de entrenamiento
clf.fit(X_train,y_train)
y_hat = clf.predict(X_test)

# Muestro el porcentaje de aciertos del clasificador
print('Porcentaje de aciertos en la clasificación: ', clf.score(X_test,y_test))

# Porcentaje de error de test
#print('Porcentaje de error del test: ', 1-clf.score(X_test,y_test))

Porcentaje de aciertos en la clasificación:  0.973684210526


In [29]:
# Punto 4:

# Obtenemos en una martiz las probabilidades de que una celula sea clasificada como maligna o benigna.
# Para cada muestra (renglon i)
# Columna 0 = probabilidad de ser clasificada como maligna
# Columna 1 = probabilidad de ser clasificada como beningna

pred_pro = clf.predict_proba(X_test)
print(pred_pro)

[[ 0.09357873  0.90642127]
 [ 0.09670674  0.90329326]
 [ 0.          1.        ]
 [ 1.          0.        ]
 [ 0.29628112  0.70371888]
 [ 1.          0.        ]
 [ 0.          1.        ]
 [ 0.          1.        ]
 [ 0.          1.        ]
 [ 0.          1.        ]
 [ 0.6368718   0.3631282 ]
 [ 0.11844013  0.88155987]
 [ 0.09596165  0.90403835]
 [ 0.          1.        ]
 [ 0.          1.        ]
 [ 1.          0.        ]
 [ 0.          1.        ]
 [ 0.          1.        ]
 [ 0.          1.        ]
 [ 1.          0.        ]
 [ 0.27112487  0.72887513]
 [ 0.          1.        ]
 [ 0.          1.        ]
 [ 0.          1.        ]
 [ 0.          1.        ]
 [ 1.          0.        ]
 [ 0.          1.        ]
 [ 0.21342515  0.78657485]
 [ 1.          0.        ]
 [ 1.          0.        ]
 [ 0.          1.        ]
 [ 0.          1.        ]
 [ 0.          1.        ]
 [ 1.          0.        ]
 [ 1.          0.        ]
 [ 0.08676328  0.91323672]
 [ 0.          1.        ]
 

In [30]:
#Teniendo en cuenta los costos de los falsos negativos (FN) y falsos positivos (FP) modifico las salidas del clasificador
FN = 20
FP = 5

from sklearn import metrics

y_hat_modificado = [] #defino un nuevo vector para guardar las nuevas salidas de clasificador

for i in range(len(pred_pro)):
    
    if pred_pro[i][1] > ((0.25) * pred_pro[i][0]):
        y_hat_modificado.append(1)
    else:
        y_hat_modificado.append(0)
   
error_matrix = metrics.confusion_matrix(y_test, y_hat_modificado)
costoFP = error_matrix[1][0] * FN
costoFN = error_matrix[0][1] * FP

costo_total = costoFP + costoFN
        
print('El costo de errores de clasificacion es: {} \nConfusion Matrix: \n {}'.format(costo_total, error_matrix))

El costo de errores de clasificacion es: 35 
Confusion Matrix: 
 [[38  7]
 [ 0 69]]


In [31]:
print(y_hat_modificado) #Imprimo la salida del clasificador modificado

[1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0]


In [32]:
#realizo la resta para poder observar de manera mas clara cuales son las muestras a las q se le cambio su clasificacion
print(y_hat - y_hat_modificado) 

[ 0  0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1  0  0  0  0
  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0]


In [35]:
# Punto 5

costo_error_prediccion = []
confusion_matrix = []

for k in range(1, X_train.shape[0]):
    data = load_breast_cancer()

    X = data.data
    y = data.target
    
    clf = neighbors.KNeighborsClassifier(n_neighbors=k, weights='distance')
    
    X_s = stats.zscore(X)
    
    X_train, X_test, y_train, y_test = train_test_split(X_s, y, random_state= rns, test_size=0.2)
    clf.fit(X_train,y_train)
    y_hat = clf.predict(X_test)
    
    pred_pro = clf.predict_proba(X_test)
    
    y_hat_modificado = []

    for i in range(len(pred_pro)):
    
        if pred_pro[i][1] > ((0.25) * pred_pro[i][0]):
            y_hat_modificado.append(1)
        else:
            y_hat_modificado.append(0)
   
    error_matrix = metrics.confusion_matrix(y_test, y_hat_modificado)
    costoFP = error_matrix[1][0] * FN
    costoFN = error_matrix[0][1] * FP

    costo = costoFP + costoFN
    
    costo_error_prediccion.append(costo)
    confusion_matrix.append(error_matrix)
    
costo_min_error_pred = min(costo_error_prediccion)
indice_min = costo_error_prediccion.index(costo_min_error_pred)+1

print('Numero de K vecinos que minimizan el costo de error de prediccion: {} \nEl costo de error de prediccion es: {} \nConfusion Matrix:\n {}' .format(indice_min, costo_min_error_pred, confusion_matrix[indice_min] ))

    

Numero de K vecinos que minimizan el costo de error de prediccion: 2 
El costo de error de prediccion es: 20 
Confusion Matrix:
 [[31  4]
 [ 0 79]]
